# Generated by Django 4.2.3 on 2023-07-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='age',
            field=models.CharField(default='18', max_length=3),
        ),
    ]
